const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('../models/User');
const Publisher = require('../models/Publisher');
const Book = require('../models/Book');

dotenv.config();

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/library_management');
    console.log('MongoDB Connected');
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

const seedData = async () => {
  try {
    await connectDB();

    // Xóa dữ liệu cũ (tùy chọn - cẩn thận trong production)
    // await User.deleteMany();
    // await Publisher.deleteMany();
    // await Book.deleteMany();

    // Tạo nhân viên thư viện mẫu
    const staff = await User.findOne({ role: 'staff' });
    if (!staff) {
      const staffUser = await User.create({
        username: 'admin',
        email: 'admin@library.com',
        password: 'admin123',
        fullName: 'Quản trị viên',
        phone: '0123456789',
        role: 'staff',
      });
      console.log('Đã tạo tài khoản nhân viên:', staffUser.username);
    }

    // Tạo độc giả mẫu
    const reader = await User.findOne({ role: 'reader', username: 'reader1' });
    if (!reader) {
      const readerUser = await User.create({
        username: 'reader1',
        email: 'reader1@example.com',
        password: '123456',
        fullName: 'Nguyễn Văn A',
        phone: '0987654321',
        address: '123 Đường ABC, Quận 1, TP.HCM',
        role: 'reader',
      });
      console.log('Đã tạo tài khoản độc giả:', readerUser.username);
    }

    // Tạo nhà xuất bản mẫu
    const publishers = [
      {
        name: 'Nhà xuất bản Giáo dục Việt Nam',
        address: '81 Trần Hưng Đạo, Hoàn Kiếm, Hà Nội',
        phone: '02438220801',
        email: 'info@nxbgd.vn',
      },
      {
        name: 'Nhà xuất bản Trẻ',
        address: '161B Lý Chính Thắng, Phường 7, Quận 3, TP.HCM',
        phone: '02839316289',
        email: 'nxbtre@nxbtre.com.vn',
      },
      {
        name: 'Nhà xuất bản Kim Đồng',
        address: '55 Quang Trung, Hai Bà Trưng, Hà Nội',
        phone: '02439434730',
        email: 'info@nxbkimdong.com.vn',
      },
      {
        name: 'Nhà xuất bản Văn học',
        address: '18 Nguyễn Trường Tộ, Ba Đình, Hà Nội',
        phone: '02438221341',
        email: 'nxbvanhoc@vnn.vn',
      },
      {
        name: 'Nhà xuất bản Tổng hợp TP.HCM',
        address: '62 Nguyễn Thị Minh Khai, Quận 3, TP.HCM',
        phone: '02839316289',
        email: 'nxbtonghop@hcm.vnn.vn',
      },
      {
        name: 'Nhà xuất bản Thế giới',
        address: '46 Trần Hưng Đạo, Hoàn Kiếm, Hà Nội',
        phone: '02438225391',
        email: 'nxbthegioi@fpt.vn',
      },
    ];

    const createdPublishers = [];
    for (const pubData of publishers) {
      let publisher = await Publisher.findOne({ name: pubData.name });
      if (!publisher) {
        publisher = await Publisher.create(pubData);
        createdPublishers.push(publisher);
      } else {
        createdPublishers.push(publisher);
      }
    }
    console.log(`Đã tạo ${createdPublishers.length} nhà xuất bản`);

    // Helper function để tạo URL ảnh bìa sách thật
    const getBookCoverImage = (isbn) => {
      // Loại bỏ dấu gạch ngang trong ISBN nếu có
      const cleanIsbn = isbn.replace(/-/g, '');
      // Ưu tiên Open Library API - ảnh lớn (L)
      // Nếu không có, có thể fallback sang Google Books: 
      // https://books.google.com/books/content?id={BOOK_ID}&printsec=frontcover&img=1&zoom=1
      // Hoặc sử dụng placeholder từ placeholder.com hoặc via.placeholder.com
      return `https://covers.openlibrary.org/b/isbn/${cleanIsbn}-L.jpg`;
    };

    // Tạo 100 cuốn sách với ảnh bìa thật
    if (createdPublishers.length > 0) {
      const books = [
        {
          title: 'Đắc Nhân Tâm',
          author: 'Dale Carnegie',
          isbn: '9786043074015',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Kỹ năng sống',
          description: 'Cuốn sách nổi tiếng về nghệ thuật ứng xử và giao tiếp trong cuộc sống và công việc. Đây là một trong những cuốn sách bán chạy nhất mọi thời đại.',
          totalCopies: 15,
          availableCopies: 12,
          coverImage: getBookCoverImage('9786043074015'),
        },
        {
          title: 'Nhà Giả Kim',
          author: 'Paulo Coelho',
          isbn: '9786043074022',
          publisher: createdPublishers[1]._id,
          publishYear: 2019,
          category: 'Văn học',
          description: 'Câu chuyện về hành trình tìm kiếm kho báu và ý nghĩa cuộc sống của một cậu bé chăn cừu. Một tác phẩm văn học đầy cảm hứng.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074022'),
        },
        {
          title: 'Tôi Tài Giỏi, Bạn Cũng Thế',
          author: 'Adam Khoo',
          isbn: '9786043074039',
          publisher: createdPublishers[0]._id,
          publishYear: 2021,
          category: 'Giáo dục',
          description: 'Phương pháp học tập hiệu quả giúp bạn đạt được thành công trong học tập và cuộc sống.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074039'),
        },
        {
          title: 'Sapiens: Lược Sử Loài Người',
          author: 'Yuval Noah Harari',
          isbn: '9786043074046',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Lịch sử',
          description: 'Cuốn sách khám phá lịch sử loài người từ thời kỳ đồ đá đến hiện đại, giải thích cách chúng ta trở thành loài thống trị Trái Đất.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074046'),
        },
        {
          title: 'Homo Deus: Lược Sử Tương Lai',
          author: 'Yuval Noah Harari',
          isbn: '9786043074053',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Khoa học',
          description: 'Tiếp nối Sapiens, tác giả dự đoán tương lai của loài người trong kỷ nguyên công nghệ và trí tuệ nhân tạo.',
          totalCopies: 7,
          availableCopies: 5,
          coverImage: getBookCoverImage('9786043074053'),
        },
        {
          title: 'Tư Duy Nhanh và Chậm',
          author: 'Daniel Kahneman',
          isbn: '9786043074060',
          publisher: createdPublishers[4]._id,
          publishYear: 2019,
          category: 'Tâm lý học',
          description: 'Khám phá hai hệ thống tư duy của con người: hệ thống nhanh (trực giác) và hệ thống chậm (phân tích).',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074060'),
        },
        {
          title: 'Đọc Vị Bất Kỳ Ai',
          author: 'David J. Lieberman',
          isbn: '9786043074077',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Tâm lý học',
          description: 'Nghệ thuật đọc vị người khác để hiểu được suy nghĩ và cảm xúc của họ trong mọi tình huống.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074077'),
        },
        {
          title: 'Người Giàu Nhất Thành Babylon',
          author: 'George S. Clason',
          isbn: '9786043074084',
          publisher: createdPublishers[1]._id,
          publishYear: 2019,
          category: 'Tài chính',
          description: 'Những nguyên tắc quản lý tài chính cổ xưa nhưng vẫn còn giá trị đến ngày nay, giúp bạn xây dựng sự giàu có.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043074084'),
        },
        {
          title: 'Dạy Con Làm Giàu',
          author: 'Robert Kiyosaki',
          isbn: '9786043074091',
          publisher: createdPublishers[1]._id,
          publishYear: 2020,
          category: 'Tài chính',
          description: 'Bộ sách nổi tiếng về giáo dục tài chính, giúp thay đổi tư duy về tiền bạc và đầu tư.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074091'),
        },
        {
          title: '7 Thói Quen Của Người Thành Đạt',
          author: 'Stephen R. Covey',
          isbn: '9786043074107',
          publisher: createdPublishers[0]._id,
          publishYear: 2021,
          category: 'Kỹ năng sống',
          description: 'Bảy thói quen quan trọng giúp bạn trở nên hiệu quả và thành công trong công việc và cuộc sống.',
          totalCopies: 14,
          availableCopies: 12,
          coverImage: getBookCoverImage('9786043074107'),
        },
        {
          title: 'Những Người Khốn Khổ',
          author: 'Victor Hugo',
          isbn: '9786043074114',
          publisher: createdPublishers[3]._id,
          publishYear: 2018,
          category: 'Văn học',
          description: 'Kiệt tác văn học Pháp về cuộc đời của Jean Valjean và những người khốn khổ trong xã hội Pháp thế kỷ 19.',
          totalCopies: 6,
          availableCopies: 4,
          coverImage: getBookCoverImage('9786043074114'),
        },
        {
          title: 'Chiến Tranh và Hòa Bình',
          author: 'Leo Tolstoy',
          isbn: '9786043074121',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Văn học',
          description: 'Tiểu thuyết sử thi vĩ đại của văn học Nga về cuộc chiến tranh Napoleon và cuộc sống của giới quý tộc Nga.',
          totalCopies: 5,
          availableCopies: 3,
          coverImage: getBookCoverImage('9786043074121'),
        },
        {
          title: 'Bố Già',
          author: 'Mario Puzo',
          isbn: '9786043074138',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện về gia đình mafia Corleone và Don Vito Corleone - bố già của gia đình.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074138'),
        },
        {
          title: 'Harry Potter và Hòn Đá Phù Thủy',
          author: 'J.K. Rowling',
          isbn: '9786043074145',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Cuốn đầu tiên trong series Harry Potter, kể về cậu bé phù thủy và cuộc phiêu lưu tại trường Hogwarts.',
          totalCopies: 20,
          availableCopies: 18,
          coverImage: getBookCoverImage('9786043074145'),
        },
        {
          title: 'Harry Potter và Phòng Chứa Bí Mật',
          author: 'J.K. Rowling',
          isbn: '9786043074152',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Cuốn thứ hai trong series, Harry và bạn bè khám phá bí mật về phòng chứa bí mật tại Hogwarts.',
          totalCopies: 18,
          availableCopies: 16,
          coverImage: getBookCoverImage('9786043074152'),
        },
        {
          title: 'Chúa Tể Những Chiếc Nhẫn',
          author: 'J.R.R. Tolkien',
          isbn: '9786043074169',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Văn học giả tưởng',
          description: 'Kiệt tác fantasy về cuộc hành trình phá hủy chiếc nhẫn quyền lực của Frodo và các bạn.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074169'),
        },
        {
          title: '1984',
          author: 'George Orwell',
          isbn: '9786043074176',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Tiểu thuyết dystopian về một xã hội bị kiểm soát hoàn toàn bởi chính phủ độc tài.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074176'),
        },
        {
          title: 'Trại Súc Vật',
          author: 'George Orwell',
          isbn: '9786043074183',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện ngụ ngôn về cuộc cách mạng của các con vật chống lại con người.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074183'),
        },
        {
          title: 'Cuốn Theo Chiều Gió',
          author: 'Margaret Mitchell',
          isbn: '9786043074190',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Văn học',
          description: 'Tiểu thuyết lịch sử về Scarlett O\'Hara trong thời kỳ Nội chiến Mỹ.',
          totalCopies: 7,
          availableCopies: 5,
          coverImage: getBookCoverImage('9786043074190'),
        },
        {
          title: 'Tiếng Gọi Nơi Hoang Dã',
          author: 'Jack London',
          isbn: '9786043074206',
          publisher: createdPublishers[1]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện về chú chó Buck và hành trình trở về với bản năng hoang dã.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074206'),
        },
        {
          title: 'Những Cuộc Phiêu Lưu Của Tom Sawyer',
          author: 'Mark Twain',
          isbn: '9786043074213',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Cuộc phiêu lưu của cậu bé Tom Sawyer và bạn bè ở miền Nam nước Mỹ.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074213'),
        },
        {
          title: 'Sherlock Holmes: Tập Truyện Ngắn',
          author: 'Arthur Conan Doyle',
          isbn: '9786043074220',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Trinh thám',
          description: 'Tập hợp các câu chuyện trinh thám nổi tiếng về thám tử Sherlock Holmes.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043074220'),
        },
        {
          title: 'Bí Mật Của Phan Thiết',
          author: 'Nguyễn Nhật Ánh',
          isbn: '9786043074237',
          publisher: createdPublishers[1]._id,
          publishYear: 2020,
          category: 'Văn học Việt Nam',
          description: 'Câu chuyện tuổi thơ đầy cảm động về tình bạn, tình yêu và những kỷ niệm đẹp.',
          totalCopies: 15,
          availableCopies: 13,
          coverImage: getBookCoverImage('9786043074237'),
        },
        {
          title: 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh',
          author: 'Nguyễn Nhật Ánh',
          isbn: '9786043074244',
          publisher: createdPublishers[1]._id,
          publishYear: 2021,
          category: 'Văn học Việt Nam',
          description: 'Những câu chuyện tuổi thơ đầy trong sáng và cảm động về làng quê Việt Nam.',
          totalCopies: 16,
          availableCopies: 14,
          coverImage: getBookCoverImage('9786043074244'),
        },
        {
          title: 'Mắt Biếc',
          author: 'Nguyễn Nhật Ánh',
          isbn: '9786043074251',
          publisher: createdPublishers[1]._id,
          publishYear: 2020,
          category: 'Văn học Việt Nam',
          description: 'Câu chuyện tình yêu đầy cảm động về mối tình đầu trong sáng và ngây thơ.',
          totalCopies: 14,
          availableCopies: 12,
          coverImage: getBookCoverImage('9786043074251'),
        },
        {
          title: 'Dế Mèn Phiêu Lưu Ký',
          author: 'Tô Hoài',
          isbn: '9786043074268',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Cuộc phiêu lưu của chú dế mèn và những bài học về cuộc sống.',
          totalCopies: 17,
          availableCopies: 15,
          coverImage: getBookCoverImage('9786043074268'),
        },
        {
          title: 'Số Đỏ',
          author: 'Vũ Trọng Phụng',
          isbn: '9786043074275',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Văn học Việt Nam',
          description: 'Tiểu thuyết châm biếm về xã hội Việt Nam đầu thế kỷ 20.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074275'),
        },
        {
          title: 'Chí Phèo',
          author: 'Nam Cao',
          isbn: '9786043074282',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Văn học Việt Nam',
          description: 'Truyện ngắn nổi tiếng về số phận người nông dân trong xã hội cũ.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074282'),
        },
        {
          title: 'Vợ Nhặt',
          author: 'Kim Lân',
          isbn: '9786043074299',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Văn học Việt Nam',
          description: 'Truyện ngắn về cuộc sống người nông dân trong nạn đói năm 1945.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074299'),
        },
        {
          title: 'Làng',
          author: 'Kim Lân',
          isbn: '9786043074305',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Văn học Việt Nam',
          description: 'Truyện ngắn về tình yêu quê hương, làng xóm của người nông dân.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074305'),
        },
        {
          title: 'Người Lái Đò Sông Đà',
          author: 'Nguyễn Tuân',
          isbn: '9786043074312',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Văn học Việt Nam',
          description: 'Tùy bút nổi tiếng về sông Đà và người lái đò dũng cảm.',
          totalCopies: 7,
          availableCopies: 5,
          coverImage: getBookCoverImage('9786043074312'),
        },
        {
          title: 'Vợ Chồng A Phủ',
          author: 'Tô Hoài',
          isbn: '9786043074329',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Văn học Việt Nam',
          description: 'Truyện ngắn về cuộc sống của người dân tộc miền núi.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074329'),
        },
        {
          title: 'Đất Rừng Phương Nam',
          author: 'Đoàn Giỏi',
          isbn: '9786043074336',
          publisher: createdPublishers[1]._id,
          publishYear: 2021,
          category: 'Văn học Việt Nam',
          description: 'Tiểu thuyết về cuộc sống ở vùng đất Nam Bộ thời kháng chiến.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074336'),
        },
        {
          title: 'Nhật Ký Đặng Thùy Trâm',
          author: 'Đặng Thùy Trâm',
          isbn: '9786043074343',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Lịch sử',
          description: 'Nhật ký của nữ bác sĩ trong chiến tranh, thể hiện tinh thần yêu nước và lý tưởng cách mạng.',
          totalCopies: 6,
          availableCopies: 4,
          coverImage: getBookCoverImage('9786043074343'),
        },
        {
          title: 'Lịch Sử Việt Nam',
          author: 'Nhiều tác giả',
          isbn: '9786043074350',
          publisher: createdPublishers[0]._id,
          publishYear: 2021,
          category: 'Lịch sử',
          description: 'Bộ sách toàn diện về lịch sử Việt Nam từ thời kỳ dựng nước đến hiện đại.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074350'),
        },
        {
          title: 'Đại Việt Sử Ký Toàn Thư',
          author: 'Ngô Sĩ Liên',
          isbn: '9786043074367',
          publisher: createdPublishers[0]._id,
          publishYear: 2019,
          category: 'Lịch sử',
          description: 'Bộ sử ký quan trọng nhất của Việt Nam, ghi chép lịch sử từ thời Hồng Bàng đến thời Lê.',
          totalCopies: 5,
          availableCopies: 3,
          coverImage: getBookCoverImage('9786043074367'),
        },
        {
          title: 'Vật Lý Vui',
          author: 'Yakov Perelman',
          isbn: '9786043074374',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Khoa học',
          description: 'Cuốn sách giúp hiểu vật lý một cách thú vị và dễ hiểu thông qua các ví dụ thực tế.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074374'),
        },
        {
          title: 'Vũ Trụ Trong Vỏ Hạt Dẻ',
          author: 'Stephen Hawking',
          isbn: '9786043074381',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Khoa học',
          description: 'Giải thích về vũ trụ, thuyết tương đối và cơ học lượng tử một cách dễ hiểu.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074381'),
        },
        {
          title: 'Lược Sử Thời Gian',
          author: 'Stephen Hawking',
          isbn: '9786043074398',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Khoa học',
          description: 'Cuốn sách nổi tiếng về vũ trụ học, giải thích nguồn gốc và tương lai của vũ trụ.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074398'),
        },
        {
          title: 'Sinh Học Phân Tử',
          author: 'Nhiều tác giả',
          isbn: '9786043074404',
          publisher: createdPublishers[0]._id,
          publishYear: 2021,
          category: 'Khoa học',
          description: 'Giáo trình về sinh học phân tử, DNA, RNA và các quá trình sinh học cơ bản.',
          totalCopies: 7,
          availableCopies: 5,
          coverImage: getBookCoverImage('9786043074404'),
        },
        {
          title: 'Hóa Học Hữu Cơ',
          author: 'Nhiều tác giả',
          isbn: '9786043074411',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Khoa học',
          description: 'Giáo trình về hóa học hữu cơ, các hợp chất carbon và phản ứng hóa học.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074411'),
        },
        {
          title: 'Toán Học Cao Cấp',
          author: 'Nhiều tác giả',
          isbn: '9786043074428',
          publisher: createdPublishers[0]._id,
          publishYear: 2021,
          category: 'Toán học',
          description: 'Giáo trình toán học cao cấp bao gồm giải tích, đại số và hình học.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074428'),
        },
        {
          title: 'Lập Trình Python',
          author: 'Nhiều tác giả',
          isbn: '9786043074435',
          publisher: createdPublishers[5]._id,
          publishYear: 2021,
          category: 'Công nghệ',
          description: 'Hướng dẫn lập trình Python từ cơ bản đến nâng cao, bao gồm các thư viện phổ biến.',
          totalCopies: 15,
          availableCopies: 13,
          coverImage: getBookCoverImage('9786043074435'),
        },
        {
          title: 'JavaScript: The Good Parts',
          author: 'Douglas Crockford',
          isbn: '9786043074442',
          publisher: createdPublishers[5]._id,
          publishYear: 2020,
          category: 'Công nghệ',
          description: 'Khám phá những phần tốt nhất của JavaScript và cách sử dụng chúng hiệu quả.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043074442'),
        },
        {
          title: 'Clean Code',
          author: 'Robert C. Martin',
          isbn: '9786043074459',
          publisher: createdPublishers[5]._id,
          publishYear: 2021,
          category: 'Công nghệ',
          description: 'Nghệ thuật viết code sạch, dễ đọc và dễ bảo trì cho các lập trình viên.',
          totalCopies: 14,
          availableCopies: 12,
          coverImage: getBookCoverImage('9786043074459'),
        },
        {
          title: 'Design Patterns',
          author: 'Gang of Four',
          isbn: '9786043074466',
          publisher: createdPublishers[5]._id,
          publishYear: 2020,
          category: 'Công nghệ',
          description: 'Các mẫu thiết kế trong lập trình hướng đối tượng, giúp giải quyết các vấn đề phổ biến.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074466'),
        },
        {
          title: 'The Pragmatic Programmer',
          author: 'Andrew Hunt',
          isbn: '9786043074473',
          publisher: createdPublishers[5]._id,
          publishYear: 2021,
          category: 'Công nghệ',
          description: 'Hướng dẫn trở thành lập trình viên thực tế và hiệu quả.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074473'),
        },
        {
          title: 'Nghệ Thuật Đàm Phán',
          author: 'Roger Fisher',
          isbn: '9786043074480',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Kinh doanh',
          description: 'Kỹ năng đàm phán hiệu quả trong kinh doanh và cuộc sống.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074480'),
        },
        {
          title: 'Từ Tốt Đến Vĩ Đại',
          author: 'Jim Collins',
          isbn: '9786043074497',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Kinh doanh',
          description: 'Nghiên cứu về cách các công ty chuyển từ tốt sang vĩ đại.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074497'),
        },
        {
          title: 'Đắc Nhân Tâm Trong Kinh Doanh',
          author: 'Dale Carnegie',
          isbn: '9786043074503',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Kinh doanh',
          description: 'Áp dụng nguyên tắc đắc nhân tâm vào lĩnh vực kinh doanh.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074503'),
        },
        {
          title: 'Khởi Nghiệp Tinh Gọn',
          author: 'Eric Ries',
          isbn: '9786043074510',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Kinh doanh',
          description: 'Phương pháp khởi nghiệp hiệu quả với tài nguyên tối thiểu.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043074510'),
        },
        {
          title: 'Nghệ Thuật Chiến Lược',
          author: 'Sun Tzu',
          isbn: '9786043074527',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Chiến lược',
          description: 'Binh pháp Tôn Tử - nghệ thuật chiến lược cổ xưa nhưng vẫn còn giá trị.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074527'),
        },
        {
          title: '48 Nguyên Tắc Quyền Lực',
          author: 'Robert Greene',
          isbn: '9786043074534',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Tâm lý học',
          description: '48 nguyên tắc để đạt được và duy trì quyền lực trong mọi tình huống.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074534'),
        },
        {
          title: 'Nghệ Thuật Tinh Tế Của Việc Đếch Quan Tâm',
          author: 'Mark Manson',
          isbn: '9786043074541',
          publisher: createdPublishers[1]._id,
          publishYear: 2021,
          category: 'Tâm lý học',
          description: 'Cách sống hạnh phúc bằng cách biết điều gì đáng quan tâm và điều gì không.',
          totalCopies: 14,
          availableCopies: 12,
          coverImage: getBookCoverImage('9786043074541'),
        },
        {
          title: 'Sức Mạnh Của Thói Quen',
          author: 'Charles Duhigg',
          isbn: '9786043074558',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Tâm lý học',
          description: 'Khám phá cách thói quen hình thành và cách thay đổi chúng để thành công.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074558'),
        },
        {
          title: 'Atomic Habits',
          author: 'James Clear',
          isbn: '9786043074565',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Tâm lý học',
          description: 'Xây dựng thói quen tốt và loại bỏ thói quen xấu một cách hiệu quả.',
          totalCopies: 15,
          availableCopies: 13,
          coverImage: getBookCoverImage('9786043074565'),
        },
        {
          title: 'Nhà Đầu Tư Thông Minh',
          author: 'Benjamin Graham',
          isbn: '9786043074572',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Tài chính',
          description: 'Hướng dẫn đầu tư chứng khoán một cách thông minh và an toàn.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074572'),
        },
        {
          title: 'Cách Nghĩ Để Thành Công',
          author: 'Napoleon Hill',
          isbn: '9786043074589',
          publisher: createdPublishers[0]._id,
          publishYear: 2021,
          category: 'Kỹ năng sống',
          description: 'Những nguyên tắc vàng để đạt được thành công trong cuộc sống.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074589'),
        },
        {
          title: 'Quẳng Gánh Lo Đi Mà Vui Sống',
          author: 'Dale Carnegie',
          isbn: '9786043074596',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Tâm lý học',
          description: 'Cách vượt qua lo lắng và sống một cuộc sống hạnh phúc hơn.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043074596'),
        },
        {
          title: 'Đọc Sách Như Một Nghệ Thuật',
          author: 'Mortimer J. Adler',
          isbn: '9786043074602',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Kỹ năng sống',
          description: 'Hướng dẫn cách đọc sách hiệu quả để tiếp thu kiến thức tốt nhất.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074602'),
        },
        {
          title: 'Nghệ Thuật Nói Trước Công Chúng',
          author: 'Dale Carnegie',
          isbn: '9786043074619',
          publisher: createdPublishers[0]._id,
          publishYear: 2020,
          category: 'Kỹ năng sống',
          description: 'Kỹ năng thuyết trình và nói trước đám đông một cách tự tin và hiệu quả.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074619'),
        },
        {
          title: 'Tâm Lý Học Đám Đông',
          author: 'Gustave Le Bon',
          isbn: '9786043074626',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Tâm lý học',
          description: 'Nghiên cứu về hành vi và tâm lý của đám đông trong xã hội.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074626'),
        },
        {
          title: 'Những Kẻ Xuất Chúng',
          author: 'Malcolm Gladwell',
          isbn: '9786043074633',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Tâm lý học',
          description: 'Khám phá những yếu tố tạo nên thành công của những người xuất chúng.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074633'),
        },
        {
          title: 'Blink: Sức Mạnh Của Suy Nghĩ Không Cần Suy Nghĩ',
          author: 'Malcolm Gladwell',
          isbn: '9786043074640',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Tâm lý học',
          description: 'Khám phá sức mạnh của trực giác và quyết định trong chớp mắt.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074640'),
        },
        {
          title: 'Outliers: Những Kẻ Xuất Chúng',
          author: 'Malcolm Gladwell',
          isbn: '9786043074657',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Tâm lý học',
          description: 'Phân tích những yếu tố tạo nên thành công vượt trội.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074657'),
        },
        {
          title: 'Tipping Point: Điểm Bùng Phát',
          author: 'Malcolm Gladwell',
          isbn: '9786043074664',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Xã hội học',
          description: 'Khám phá cách những ý tưởng, sản phẩm lan truyền và trở thành xu hướng.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074664'),
        },
        {
          title: 'Sapiens: Lược Sử Ngắn Gọn Của Nhân Loại',
          author: 'Yuval Noah Harari',
          isbn: '9786043074671',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Lịch sử',
          description: 'Phiên bản tóm tắt của cuốn Sapiens, dễ đọc và dễ hiểu hơn.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074671'),
        },
        {
          title: '21 Bài Học Cho Thế Kỷ 21',
          author: 'Yuval Noah Harari',
          isbn: '9786043074688',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Xã hội học',
          description: '21 bài học về các thách thức và cơ hội của thế kỷ 21.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074688'),
        },
        {
          title: 'Sự Im Lặng Của Bầy Cừu',
          author: 'Thomas Harris',
          isbn: '9786043074695',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Trinh thám',
          description: 'Tiểu thuyết trinh thám nổi tiếng về Hannibal Lecter và cuộc điều tra của Clarice Starling.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074695'),
        },
        {
          title: 'Mật Mã Da Vinci',
          author: 'Dan Brown',
          isbn: '9786043074701',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Trinh thám',
          description: 'Cuộc phiêu lưu của Robert Langdon để giải mã bí mật cổ xưa.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043074701'),
        },
        {
          title: 'Thiên Thần và Ác Quỷ',
          author: 'Dan Brown',
          isbn: '9786043074718',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Trinh thám',
          description: 'Cuộc điều tra của Robert Langdon về một âm mưu chống lại Vatican.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074718'),
        },
        {
          title: 'Inferno',
          author: 'Dan Brown',
          isbn: '9786043074725',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Trinh thám',
          description: 'Cuộc chạy đua với thời gian để ngăn chặn một đại dịch toàn cầu.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074725'),
        },
        {
          title: 'Biên Niên Sử Narnia',
          author: 'C.S. Lewis',
          isbn: '9786043074732',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Bộ truyện fantasy về thế giới Narnia và những cuộc phiêu lưu kỳ diệu.',
          totalCopies: 16,
          availableCopies: 14,
          coverImage: getBookCoverImage('9786043074732'),
        },
        {
          title: 'Hobbit',
          author: 'J.R.R. Tolkien',
          isbn: '9786043074749',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Văn học giả tưởng',
          description: 'Cuộc phiêu lưu của Bilbo Baggins và những người lùn để giành lại kho báu.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074749'),
        },
        {
          title: 'Game of Thrones',
          author: 'George R.R. Martin',
          isbn: '9786043074756',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Văn học giả tưởng',
          description: 'Cuốn đầu tiên trong series A Song of Ice and Fire về cuộc chiến giành ngai sắt.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074756'),
        },
        {
          title: 'Dune',
          author: 'Frank Herbert',
          isbn: '9786043074763',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Khoa học viễn tưởng',
          description: 'Tiểu thuyết khoa học viễn tưởng về hành tinh Arrakis và gia đình Atreides.',
          totalCopies: 7,
          availableCopies: 5,
          coverImage: getBookCoverImage('9786043074763'),
        },
        {
          title: 'Foundation',
          author: 'Isaac Asimov',
          isbn: '9786043074770',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Khoa học viễn tưởng',
          description: 'Cuốn đầu tiên trong series Foundation về sự sụp đổ và tái thiết của Đế chế Galaxy.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074770'),
        },
        {
          title: 'Neuromancer',
          author: 'William Gibson',
          isbn: '9786043074787',
          publisher: createdPublishers[5]._id,
          publishYear: 2020,
          category: 'Khoa học viễn tưởng',
          description: 'Tiểu thuyết cyberpunk về hacker Case và thế giới mạng trong tương lai.',
          totalCopies: 6,
          availableCopies: 4,
          coverImage: getBookCoverImage('9786043074787'),
        },
        {
          title: 'Ender\'s Game',
          author: 'Orson Scott Card',
          isbn: '9786043074794',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Khoa học viễn tưởng',
          description: 'Câu chuyện về Ender Wiggin, một đứa trẻ thiên tài được huấn luyện để chiến đấu với người ngoài hành tinh.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074794'),
        },
        {
          title: 'The Hunger Games',
          author: 'Suzanne Collins',
          isbn: '9786043074800',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Cuốn đầu tiên trong series về Katniss Everdeen và cuộc chiến sinh tồn.',
          totalCopies: 14,
          availableCopies: 12,
          coverImage: getBookCoverImage('9786043074800'),
        },
        {
          title: 'Divergent',
          author: 'Veronica Roth',
          isbn: '9786043074817',
          publisher: createdPublishers[2]._id,
          publishYear: 2020,
          category: 'Văn học thiếu nhi',
          description: 'Câu chuyện về Tris Prior trong một xã hội được chia thành các phe phái.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043074817'),
        },
        {
          title: 'The Maze Runner',
          author: 'James Dashner',
          isbn: '9786043074824',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Cuộc phiêu lưu của Thomas trong mê cung bí ẩn để tìm cách thoát ra.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074824'),
        },
        {
          title: 'Percy Jackson và Các Vị Thần',
          author: 'Rick Riordan',
          isbn: '9786043074831',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Cuộc phiêu lưu của Percy Jackson, con trai của thần biển Poseidon.',
          totalCopies: 15,
          availableCopies: 13,
          coverImage: getBookCoverImage('9786043074831'),
        },
        {
          title: 'Artemis Fowl',
          author: 'Eoin Colfer',
          isbn: '9786043074848',
          publisher: createdPublishers[2]._id,
          publishYear: 2020,
          category: 'Văn học thiếu nhi',
          description: 'Câu chuyện về Artemis Fowl, một thiên tài trẻ tuổi và thế giới thần tiên.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074848'),
        },
        {
          title: 'The Giver',
          author: 'Lois Lowry',
          isbn: '9786043074855',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Câu chuyện về Jonas trong một xã hội không có cảm xúc và ký ức.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074855'),
        },
        {
          title: 'Charlotte\'s Web',
          author: 'E.B. White',
          isbn: '9786043074862',
          publisher: createdPublishers[2]._id,
          publishYear: 2020,
          category: 'Văn học thiếu nhi',
          description: 'Câu chuyện cảm động về tình bạn giữa chú lợn Wilbur và cô nhện Charlotte.',
          totalCopies: 14,
          availableCopies: 12,
          coverImage: getBookCoverImage('9786043074862'),
        },
        {
          title: 'The Little Prince',
          author: 'Antoine de Saint-Exupéry',
          isbn: '9786043074879',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Câu chuyện triết học về hoàng tử nhỏ và những bài học về cuộc sống.',
          totalCopies: 16,
          availableCopies: 14,
          coverImage: getBookCoverImage('9786043074879'),
        },
        {
          title: 'Alice ở Xứ Sở Thần Tiên',
          author: 'Lewis Carroll',
          isbn: '9786043074886',
          publisher: createdPublishers[2]._id,
          publishYear: 2020,
          category: 'Văn học thiếu nhi',
          description: 'Cuộc phiêu lưu kỳ diệu của Alice vào xứ sở thần tiên đầy phép thuật.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043074886'),
        },
        {
          title: 'Peter Pan',
          author: 'J.M. Barrie',
          isbn: '9786043074893',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Câu chuyện về cậu bé không bao giờ lớn và xứ sở Neverland.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074893'),
        },
        {
          title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
          author: 'C.S. Lewis',
          isbn: '9786043074909',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Cuốn đầu tiên trong series Narnia về bốn đứa trẻ và thế giới Narnia.',
          totalCopies: 15,
          availableCopies: 13,
          coverImage: getBookCoverImage('9786043074909'),
        },
        {
          title: 'To Kill a Mockingbird',
          author: 'Harper Lee',
          isbn: '9786043074916',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện về sự phân biệt chủng tộc và công lý ở miền Nam nước Mỹ.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074916'),
        },
        {
          title: 'The Great Gatsby',
          author: 'F. Scott Fitzgerald',
          isbn: '9786043074923',
          publisher: createdPublishers[3]._id,
          publishYear: 2019,
          category: 'Văn học',
          description: 'Tiểu thuyết về thời đại Jazz và giấc mơ Mỹ trong những năm 1920.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074923'),
        },
        {
          title: 'Pride and Prejudice',
          author: 'Jane Austen',
          isbn: '9786043074930',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện tình yêu cổ điển về Elizabeth Bennet và Mr. Darcy.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043074930'),
        },
        {
          title: 'Jane Eyre',
          author: 'Charlotte Brontë',
          isbn: '9786043074947',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Văn học',
          description: 'Tiểu thuyết về cuộc đời của Jane Eyre từ thời thơ ấu đến khi trưởng thành.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074947'),
        },
        {
          title: 'Wuthering Heights',
          author: 'Emily Brontë',
          isbn: '9786043074954',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện tình yêu đầy đam mê và bi kịch giữa Heathcliff và Catherine.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043074954'),
        },
        {
          title: 'The Catcher in the Rye',
          author: 'J.D. Salinger',
          isbn: '9786043074961',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Văn học',
          description: 'Câu chuyện về Holden Caulfield và những suy nghĩ về cuộc sống và xã hội.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074961'),
        },
        {
          title: 'Lord of the Flies',
          author: 'William Golding',
          isbn: '9786043074978',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện về một nhóm trẻ em bị mắc kẹt trên đảo hoang và sự suy đồi của xã hội.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043074978'),
        },
        {
          title: 'The Kite Runner',
          author: 'Khaled Hosseini',
          isbn: '9786043074985',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Văn học',
          description: 'Câu chuyện về tình bạn, sự phản bội và cứu chuộc ở Afghanistan.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043074985'),
        },
        {
          title: 'A Thousand Splendid Suns',
          author: 'Khaled Hosseini',
          isbn: '9786043074992',
          publisher: createdPublishers[3]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện về hai người phụ nữ Afghanistan và cuộc sống của họ qua các thời kỳ.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043074992'),
        },
        {
          title: 'The Alchemist',
          author: 'Paulo Coelho',
          isbn: '9786043075005',
          publisher: createdPublishers[1]._id,
          publishYear: 2021,
          category: 'Văn học',
          description: 'Câu chuyện về hành trình tìm kiếm kho báu và ý nghĩa cuộc sống của một cậu bé chăn cừu.',
          totalCopies: 13,
          availableCopies: 11,
          coverImage: getBookCoverImage('9786043075005'),
        },
        {
          title: 'Life of Pi',
          author: 'Yann Martel',
          isbn: '9786043075012',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Văn học',
          description: 'Câu chuyện về Pi và con hổ Richard Parker trên một chiếc thuyền cứu hộ.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043075012'),
        },
        {
          title: 'The Book Thief',
          author: 'Markus Zusak',
          isbn: '9786043075029',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học',
          description: 'Câu chuyện về Liesel, một cô bé Đức trong Thế chiến II và sức mạnh của sách.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043075029'),
        },
        {
          title: 'The Fault in Our Stars',
          author: 'John Green',
          isbn: '9786043075036',
          publisher: createdPublishers[2]._id,
          publishYear: 2020,
          category: 'Văn học thiếu nhi',
          description: 'Câu chuyện tình yêu cảm động giữa Hazel và Augustus, hai thanh thiếu niên mắc bệnh ung thư.',
          totalCopies: 14,
          availableCopies: 12,
          coverImage: getBookCoverImage('9786043075036'),
        },
        {
          title: 'Looking for Alaska',
          author: 'John Green',
          isbn: '9786043075043',
          publisher: createdPublishers[2]._id,
          publishYear: 2021,
          category: 'Văn học thiếu nhi',
          description: 'Câu chuyện về Miles và cuộc tìm kiếm "Great Perhaps" của anh tại trường nội trú.',
          totalCopies: 11,
          availableCopies: 9,
          coverImage: getBookCoverImage('9786043075043'),
        },
        {
          title: 'Paper Towns',
          author: 'John Green',
          isbn: '9786043075050',
          publisher: createdPublishers[2]._id,
          publishYear: 2020,
          category: 'Văn học thiếu nhi',
          description: 'Cuộc tìm kiếm của Quentin để tìm Margo, người bạn thời thơ ấu đã biến mất.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043075050'),
        },
        {
          title: 'The Help',
          author: 'Kathryn Stockett',
          isbn: '9786043075067',
          publisher: createdPublishers[3]._id,
          publishYear: 2021,
          category: 'Văn học',
          description: 'Câu chuyện về những người phụ nữ da đen làm giúp việc ở Mississippi trong những năm 1960.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043075067'),
        },
        {
          title: 'Gone Girl',
          author: 'Gillian Flynn',
          isbn: '9786043075074',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Trinh thám',
          description: 'Tiểu thuyết tâm lý trinh thám về sự biến mất của Amy và cuộc điều tra của chồng cô.',
          totalCopies: 12,
          availableCopies: 10,
          coverImage: getBookCoverImage('9786043075074'),
        },
        {
          title: 'The Girl with the Dragon Tattoo',
          author: 'Stieg Larsson',
          isbn: '9786043075081',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Trinh thám',
          description: 'Cuộc điều tra của Mikael Blomkvist và Lisbeth Salander về một vụ án bí ẩn.',
          totalCopies: 10,
          availableCopies: 8,
          coverImage: getBookCoverImage('9786043075081'),
        },
        {
          title: 'The Shining',
          author: 'Stephen King',
          isbn: '9786043075098',
          publisher: createdPublishers[4]._id,
          publishYear: 2020,
          category: 'Kinh dị',
          description: 'Câu chuyện kinh dị về gia đình Torrance và khách sạn Overlook đầy ám ảnh.',
          totalCopies: 8,
          availableCopies: 6,
          coverImage: getBookCoverImage('9786043075098'),
        },
        {
          title: 'It',
          author: 'Stephen King',
          isbn: '9786043075104',
          publisher: createdPublishers[4]._id,
          publishYear: 2021,
          category: 'Kinh dị',
          description: 'Câu chuyện về một nhóm bạn thời thơ ấu và con quỷ Pennywise.',
          totalCopies: 9,
          availableCopies: 7,
          coverImage: getBookCoverImage('9786043075104'),
        },
      ];

      let createdCount = 0;
      for (const bookData of books) {
        const existingBook = await Book.findOne({ isbn: bookData.isbn });
        if (!existingBook) {
          await Book.create(bookData);
          createdCount++;
        }
      }
      console.log(`Đã tạo ${createdCount} cuốn sách mẫu`);
    }

    console.log('✅ Hoàn tất seed data!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Lỗi khi seed data:', error);
    process.exit(1);
  }
};

seedData();
